### PR TITLE
Changes in css

### PR DESCRIPTION
**Pull request by ayush9398**
Hi, 
I am new at github and saw your issues. I added some changes in css.

### CODE REVIEW

**Comment by arch-master** [comment]
@ayush9398 Thank you! I will look over your changes.

**Comment by arch-master** [comment]
@ayush9398 1) Where did you get the images? They are awesome! 2) Can you give me write access to your fork of eBooker? I need to see something. Go [here](https://github.com/ayush9398/eBooker/settings/collaboration) and type in `arch-master`. 3) I have a friend named Aakash Mittal!

**Comment by ayush9398** [comment]
I'm glad that you liked it.
I got the pics from google...
I have sent you the invite....

**Comment by arch-master** [comment]
@ayush9398 Thanks!

**Pull request closed without merging**
